module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- For more details, see http://developer.anscamobile.com/reference/sprite-sheets

local M = {}

local getSheetOptions = function()
	local options = {
		frames = {
		
			{
				x = 0,
				y = 0,
				width = 17,
				height = 17
			},
		
			{
				x = 18,
				y = 0,
				width = 11,
				height = 17
			},
		
			{
				x = 29,
				y = 0,
				width = 11,
				height = 17
			},
		
			{
				x = 41,
				y = 0,
				width = 10,
				height = 17
			},
		
			{
				x = 52,
				y = 0,
				width = 10,
				height = 17
			},
		
			{
				x = 62,
				y = 0,
				width = 15,
				height = 18
			},
		
			{
				x = 78,
				y = 0,
				width = 14,
				height = 18
			},
		
			{
				x = 94,
				y = 0,
				width = 14,
				height = 18
			},
		
			{
				x = 109,
				y = 0,
				width = 15,
				height = 19
			},
		
			{
				x = 125,
				y = 0,
				width = 15,
				height = 19
			},
		
			{
				x = 141,
				y = 0,
				width = 15,
				height = 19
			},
		
			{
				x = 157,
				y = 0,
				width = 17,
				height = 19
			},
		
			{
				x = 175,
				y = 0,
				width = 19,
				height = 18
			},
		
			{
				x = 195,
				y = 0,
				width = 17,
				height = 17
			},
		
			{
				x = 213,
				y = 0,
				width = 11,
				height = 17
			},
		
			{
				x = 225,
				y = 0,
				width = 10,
				height = 17
			},
		
			{
				x = 236,
				y = 0,
				width = 11,
				height = 17
			},
		
			{
				x = 248,
				y = 0,
				width = 11,
				height = 17
			},
		
			{
				x = 260,
				y = 0,
				width = 11,
				height = 17
			},
		
			{
				x = 272,
				y = 0,
				width = 13,
				height = 17
			},
		
			{
				x = 286,
				y = 0,
				width = 14,
				height = 17
			},
		
			{
				x = 301,
				y = 0,
				width = 17,
				height = 17
			},
		
			{
				x = 319,
				y = 0,
				width = 8,
				height = 17
			},
		
			{
				x = 329,
				y = 0,
				width = 8,
				height = 17
			},
		
			{
				x = 338,
				y = 0,
				width = 8,
				height = 17
			},
		
			{
				x = 347,
				y = 0,
				width = 8,
				height = 17
			},
		
			{
				x = 356,
				y = 0,
				width = 8,
				height = 18
			},
		
			{
				x = 365,
				y = 0,
				width = 12,
				height = 18
			},
		
			{
				x = 377,
				y = 0,
				width = 15,
				height = 18
			},
		
			{
				x = 393,
				y = 0,
				width = 15,
				height = 18
			},
		
			{
				x = 409,
				y = 0,
				width = 15,
				height = 18
			},
		
			{
				x = 426,
				y = 0,
				width = 16,
				height = 18
			},
		
			{
				x = 443,
				y = 0,
				width = 17,
				height = 18
			},
		
			{
				x = 460,
				y = 0,
				width = 13,
				height = 20
			},
		
			{
				x = 474,
				y = 0,
				width = 13,
				height = 20
			},
		
			{
				x = 488,
				y = 0,
				width = 15,
				height = 20
			},
		
			{
				x = 504,
				y = 0,
				width = 11,
				height = 20
			},
		
			{
				x = 516,
				y = 0,
				width = 12,
				height = 20
			},
		
			{
				x = 528,
				y = 0,
				width = 15,
				height = 20
			},
		
			{
				x = 544,
				y = 0,
				width = 33,
				height = 33
			},
		
			{
				x = 578,
				y = 0,
				width = 33,
				height = 33
			},
		
			{
				x = 612,
				y = 0,
				width = 17,
				height = 17
			},
		
			{
				x = 630,
				y = 0,
				width = 20,
				height = 30
			},
		
			{
				x = 0,
				y = 33,
				width = 480,
				height = 276
			},
		
			{
				x = 480,
				y = 33,
				width = 11,
				height = 17
			},
		
			{
				x = 492,
				y = 33,
				width = 11,
				height = 17
			},
		
			{
				x = 504,
				y = 33,
				width = 10,
				height = 17
			},
		
			{
				x = 514,
				y = 33,
				width = 10,
				height = 17
			},
		
			{
				x = 525,
				y = 33,
				width = 15,
				height = 18
			},
		
			{
				x = 541,
				y = 33,
				width = 14,
				height = 18
			},
		
			{
				x = 557,
				y = 33,
				width = 14,
				height = 18
			},
		
			{
				x = 572,
				y = 33,
				width = 15,
				height = 19
			},
		
			{
				x = 587,
				y = 33,
				width = 15,
				height = 19
			},
		
			{
				x = 603,
				y = 33,
				width = 15,
				height = 19
			},
		
			{
				x = 619,
				y = 33,
				width = 17,
				height = 19
			},
		
			{
				x = 637,
				y = 33,
				width = 19,
				height = 18
			},
		
			{
				x = 657,
				y = 33,
				width = 300,
				height = 140
			},
		
			{
				x = 0,
				y = 309,
				width = 300,
				height = 140
			},
		
			{
				x = 300,
				y = 309,
				width = 300,
				height = 130
			},
		
			{
				x = 601,
				y = 309,
				width = 42,
				height = 210
			},
		
			{
				x = 644,
				y = 309,
				width = 1,
				height = 4
			},
		
			{
				x = 645,
				y = 309,
				width = 1,
				height = 4
			},
		
			{
				x = 646,
				y = 309,
				width = 1,
				height = 4
			},
		
			{
				x = 647,
				y = 309,
				width = 1,
				height = 4
			},
		
			{
				x = 648,
				y = 309,
				width = 1,
				height = 4
			},
		
			{
				x = 649,
				y = 309,
				width = 129,
				height = 43
			},
		
			{
				x = 779,
				y = 309,
				width = 129,
				height = 43
			},
		
			{
				x = 909,
				y = 309,
				width = 41,
				height = 32
			},
		
			{
				x = 951,
				y = 309,
				width = 23,
				height = 52
			},
		
			{
				x = 975,
				y = 309,
				width = 15,
				height = 15
			},
		
			{
				x = 991,
				y = 309,
				width = 15,
				height = 15
			},
		
			{
				x = 1006,
				y = 309,
				width = 15,
				height = 17
			},
		
			{
				x = 0,
				y = 519,
				width = 16,
				height = 18
			},
		
			{
				x = 17,
				y = 519,
				width = 16,
				height = 18
			},
		
			{
				x = 34,
				y = 519,
				width = 17,
				height = 20
			},
		
			{
				x = 52,
				y = 519,
				width = 18,
				height = 21
			},
		
			{
				x = 71,
				y = 519,
				width = 20,
				height = 23
			},
		
			{
				x = 92,
				y = 519,
				width = 18,
				height = 23
			},
		
			{
				x = 111,
				y = 519,
				width = 20,
				height = 24
			},
		
			{
				x = 131,
				y = 519,
				width = 19,
				height = 24
			},
		
			{
				x = 152,
				y = 519,
				width = 20,
				height = 24
			},
		
			{
				x = 172,
				y = 519,
				width = 20,
				height = 25
			},
		
			{
				x = 193,
				y = 519,
				width = 20,
				height = 23
			},
		
			{
				x = 215,
				y = 519,
				width = 10,
				height = 10
			},
		
			{
				x = 225,
				y = 519,
				width = 10,
				height = 10
			},
		
			{
				x = 236,
				y = 519,
				width = 12,
				height = 12
			},
		
			{
				x = 249,
				y = 519,
				width = 12,
				height = 12
			},
		
			{
				x = 262,
				y = 519,
				width = 12,
				height = 12
			},
		
			{
				x = 275,
				y = 519,
				width = 13,
				height = 12
			},
		
			{
				x = 289,
				y = 519,
				width = 13,
				height = 13
			},
		
			{
				x = 303,
				y = 519,
				width = 13,
				height = 14
			},
		
			{
				x = 317,
				y = 519,
				width = 13,
				height = 14
			},
		
			{
				x = 331,
				y = 519,
				width = 14,
				height = 15
			},
		
			{
				x = 346,
				y = 519,
				width = 14,
				height = 15
			},
		
			{
				x = 361,
				y = 519,
				width = 25,
				height = 15
			},
		
			{
				x = 387,
				y = 519,
				width = 25,
				height = 15
			},
		
			{
				x = 412,
				y = 519,
				width = 28,
				height = 17
			},
		
			{
				x = 441,
				y = 519,
				width = 28,
				height = 18
			},
		
			{
				x = 470,
				y = 519,
				width = 28,
				height = 20
			},
		
			{
				x = 499,
				y = 519,
				width = 27,
				height = 20
			},
		
			{
				x = 527,
				y = 519,
				width = 28,
				height = 20
			},
		
			{
				x = 556,
				y = 519,
				width = 26,
				height = 19
			},
		
			{
				x = 583,
				y = 519,
				width = 26,
				height = 19
			},
		
			{
				x = 610,
				y = 519,
				width = 26,
				height = 19
			},
		
			{
				x = 637,
				y = 519,
				width = 25,
				height = 19
			},
		
			{
				x = 663,
				y = 519,
				width = 40,
				height = 25
			},
		
			{
				x = 703,
				y = 519,
				width = 40,
				height = 25
			},
		
			{
				x = 744,
				y = 519,
				width = 39,
				height = 24
			},
		
			{
				x = 784,
				y = 519,
				width = 40,
				height = 25
			},
		
			{
				x = 825,
				y = 519,
				width = 39,
				height = 28
			},
		
			{
				x = 865,
				y = 519,
				width = 39,
				height = 28
			},
		
			{
				x = 905,
				y = 519,
				width = 40,
				height = 28
			},
		
			{
				x = 945,
				y = 519,
				width = 37,
				height = 27
			},
		
			{
				x = 984,
				y = 519,
				width = 37,
				height = 27
			},
		
			{
				x = 0,
				y = 549,
				width = 37,
				height = 27
			},
		
			{
				x = 37,
				y = 549,
				width = 36,
				height = 27
			},
		
			{
				x = 74,
				y = 549,
				width = 10,
				height = 25
			},
		
			{
				x = 84,
				y = 549,
				width = 10,
				height = 25
			},
		
			{
				x = 95,
				y = 549,
				width = 11,
				height = 26
			},
		
			{
				x = 107,
				y = 549,
				width = 11,
				height = 26
			},
		
			{
				x = 118,
				y = 549,
				width = 12,
				height = 28
			},
		
			{
				x = 131,
				y = 549,
				width = 14,
				height = 30
			},
		
			{
				x = 146,
				y = 549,
				width = 14,
				height = 30
			},
		
			{
				x = 160,
				y = 549,
				width = 14,
				height = 29
			},
		
			{
				x = 175,
				y = 549,
				width = 13,
				height = 28
			},
		
			{
				x = 189,
				y = 549,
				width = 15,
				height = 28
			},
		
			{
				x = 205,
				y = 549,
				width = 15,
				height = 27
			},
		
			{
				x = 221,
				y = 549,
				width = 5,
				height = 50
			},
		
			{
				x = 227,
				y = 549,
				width = 5,
				height = 50
			},
		
			{
				x = 232,
				y = 549,
				width = 7,
				height = 55
			},
		
			{
				x = 240,
				y = 549,
				width = 7,
				height = 56
			},
		
			{
				x = 248,
				y = 549,
				width = 7,
				height = 55
			},
		
			{
				x = 256,
				y = 549,
				width = 7,
				height = 55
			},
		
			{
				x = 264,
				y = 549,
				width = 7,
				height = 53
			},
		
			{
				x = 272,
				y = 549,
				width = 7,
				height = 51
			},
		
			{
				x = 280,
				y = 549,
				width = 7,
				height = 50
			},
		
			{
				x = 288,
				y = 549,
				width = 8,
				height = 51
			},
		
			{
				x = 297,
				y = 549,
				width = 25,
				height = 10
			},
		
			{
				x = 322,
				y = 549,
				width = 25,
				height = 10
			},
		
			{
				x = 348,
				y = 549,
				width = 26,
				height = 11
			},
		
			{
				x = 374,
				y = 549,
				width = 27,
				height = 13
			},
		
			{
				x = 402,
				y = 549,
				width = 27,
				height = 14
			},
		
			{
				x = 430,
				y = 549,
				width = 27,
				height = 14
			},
		
			{
				x = 458,
				y = 549,
				width = 28,
				height = 14
			},
		
			{
				x = 487,
				y = 549,
				width = 28,
				height = 14
			},
		
			{
				x = 516,
				y = 549,
				width = 28,
				height = 14
			},
		
			{
				x = 545,
				y = 549,
				width = 28,
				height = 14
			},
		
			{
				x = 574,
				y = 549,
				width = 28,
				height = 14
			},
		
			{
				x = 603,
				y = 549,
				width = 15,
				height = 10
			},
		
			{
				x = 619,
				y = 549,
				width = 15,
				height = 10
			},
		
			{
				x = 634,
				y = 549,
				width = 15,
				height = 10
			},
		
			{
				x = 650,
				y = 549,
				width = 16,
				height = 11
			},
		
			{
				x = 667,
				y = 549,
				width = 16,
				height = 11
			},
		
			{
				x = 684,
				y = 549,
				width = 16,
				height = 11
			},
		
			{
				x = 701,
				y = 549,
				width = 16,
				height = 12
			},
		
			{
				x = 717,
				y = 549,
				width = 16,
				height = 12
			},
		
			{
				x = 734,
				y = 549,
				width = 17,
				height = 12
			},
		
			{
				x = 752,
				y = 549,
				width = 17,
				height = 12
			},
		
			{
				x = 770,
				y = 549,
				width = 17,
				height = 12
			},
		
			{
				x = 787,
				y = 549,
				width = 5,
				height = 5
			},
		
			{
				x = 793,
				y = 549,
				width = 5,
				height = 5
			},
		
			{
				x = 799,
				y = 549,
				width = 6,
				height = 6
			},
		
			{
				x = 805,
				y = 549,
				width = 6,
				height = 6
			},
		
			{
				x = 812,
				y = 549,
				width = 6,
				height = 6
			},
		
			{
				x = 818,
				y = 549,
				width = 5,
				height = 5
			},
		
			{
				x = 824,
				y = 549,
				width = 5,
				height = 5
			},
		
			{
				x = 830,
				y = 549,
				width = 5,
				height = 4
			},
		
			{
				x = 836,
				y = 549,
				width = 20,
				height = 5
			},
		
			{
				x = 856,
				y = 549,
				width = 20,
				height = 5
			},
		
			{
				x = 877,
				y = 549,
				width = 20,
				height = 5
			},
		
			{
				x = 897,
				y = 549,
				width = 20,
				height = 5
			},
		
			{
				x = 918,
				y = 549,
				width = 22,
				height = 6
			},
		
			{
				x = 940,
				y = 549,
				width = 23,
				height = 7
			},
		
			{
				x = 964,
				y = 549,
				width = 21,
				height = 6
			},
		
			{
				x = 985,
				y = 549,
				width = 20,
				height = 6
			},
		
			{
				x = 0,
				y = 605,
				width = 20,
				height = 5
			},
		
			{
				x = 20,
				y = 605,
				width = 20,
				height = 5
			},
		
			{
				x = 41,
				y = 605,
				width = 20,
				height = 4
			},
		
			{
				x = 61,
				y = 605,
				width = 20,
				height = 10
			},
		
			{
				x = 82,
				y = 605,
				width = 20,
				height = 10
			},
		
			{
				x = 102,
				y = 605,
				width = 20,
				height = 10
			},
		
			{
				x = 123,
				y = 605,
				width = 20,
				height = 10
			},
		
			{
				x = 143,
				y = 605,
				width = 22,
				height = 10
			},
		
			{
				x = 166,
				y = 605,
				width = 23,
				height = 10
			},
		
			{
				x = 189,
				y = 605,
				width = 21,
				height = 10
			},
		
			{
				x = 211,
				y = 605,
				width = 20,
				height = 10
			},
		
			{
				x = 232,
				y = 605,
				width = 20,
				height = 11
			},
		
			{
				x = 252,
				y = 605,
				width = 20,
				height = 10
			},
		
			{
				x = 273,
				y = 605,
				width = 20,
				height = 9
			},
		
			{
				x = 293,
				y = 605,
				width = 11,
				height = 10
			},
		
			{
				x = 305,
				y = 605,
				width = 11,
				height = 10
			},
		
			{
				x = 317,
				y = 605,
				width = 10,
				height = 10
			},
		
			{
				x = 328,
				y = 605,
				width = 10,
				height = 10
			},
		
			{
				x = 338,
				y = 605,
				width = 70,
				height = 67
			},
		
			{
				x = 409,
				y = 605,
				width = 99,
				height = 35
			},
		
			{
				x = 509,
				y = 605,
				width = 70,
				height = 67
			},
		
			{
				x = 580,
				y = 605,
				width = 70,
				height = 67
			},
		
			{
				x = 651,
				y = 605,
				width = 70,
				height = 67
			},
		
			{
				x = 722,
				y = 605,
				width = 70,
				height = 67
			},
		
			{
				x = 793,
				y = 605,
				width = 45,
				height = 31
			},
		
			{
				x = 839,
				y = 605,
				width = 31,
				height = 55
			},
		
			{
				x = 0,
				y = 673,
				width = 240,
				height = 25
			},
		
			{
				x = 240,
				y = 673,
				width = 50,
				height = 50
			},
		
			{
				x = 291,
				y = 673,
				width = 85,
				height = 15
			},
		
			{
				x = 376,
				y = 673,
				width = 10,
				height = 10
			},
		
			{
				x = 387,
				y = 673,
				width = 50,
				height = 5
			},
		
			{
				x = 437,
				y = 673,
				width = 25,
				height = 25
			},
		
			{
				x = 463,
				y = 673,
				width = 25,
				height = 25
			},
		
			{
				x = 488,
				y = 673,
				width = 25,
				height = 15
			},
		
		},
		
		sheetContentWidth = 1024,
		sheetContentHeight = 1024
	}

	return options
end
M.getSheetOptions = getSheetOptions

return M