module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- For more details, see http://developer.anscamobile.com/reference/sprite-sheets

local M = {}

local getSheetOptions = function()
	local options = {
		frames = {
		
			{
				x = 0,
				y = 0,
				width = 480,
				height = 360
			},
		
			{
				x = 481,
				y = 0,
				width = 480,
				height = 360
			},
		
			{
				x = 962,
				y = 0,
				width = 8,
				height = 1
			},
		
			{
				x = 971,
				y = 0,
				width = 8,
				height = 1
			},
		
			{
				x = 0,
				y = 361,
				width = 430,
				height = 132
			},
		
			{
				x = 431,
				y = 361,
				width = 8,
				height = 1
			},
		
			{
				x = 440,
				y = 361,
				width = 138,
				height = 137
			},
		
			{
				x = 580,
				y = 361,
				width = 132,
				height = 98
			},
		
			{
				x = 713,
				y = 361,
				width = 10,
				height = 10
			},
		
			{
				x = 724,
				y = 361,
				width = 10,
				height = 10
			},
		
			{
				x = 735,
				y = 361,
				width = 10,
				height = 10
			},
		
			{
				x = 747,
				y = 361,
				width = 11,
				height = 10
			},
		
			{
				x = 759,
				y = 361,
				width = 12,
				height = 10
			},
		
			{
				x = 772,
				y = 361,
				width = 13,
				height = 11
			},
		
			{
				x = 786,
				y = 361,
				width = 15,
				height = 13
			},
		
			{
				x = 802,
				y = 361,
				width = 14,
				height = 12
			},
		
			{
				x = 817,
				y = 361,
				width = 11,
				height = 10
			},
		
			{
				x = 830,
				y = 361,
				width = 10,
				height = 9
			},
		
			{
				x = 841,
				y = 361,
				width = 8,
				height = 7
			},
		
			{
				x = 850,
				y = 361,
				width = 6,
				height = 5
			},
		
			{
				x = 858,
				y = 361,
				width = 160,
				height = 337
			},
		
			{
				x = 0,
				y = 699,
				width = 33,
				height = 33
			},
		
		},
		
		sheetContentWidth = 1024,
		sheetContentHeight = 1024
	}

	return options
end
M.getSheetOptions = getSheetOptions

return M