module(...)

-- This file is for use with CoronaSDK™ and was generated by Zwoptex (http://zwoptexapp.com/)
--
-- For more details, see http://developer.anscamobile.com/reference/sprite-sheets

local M = {}

local getSheetOptions = function()
	local options = {
		frames = {
		
			{
				x = 0,
				y = 0,
				width = 301,
				height = 141
			},
		
			{
				x = 302,
				y = 0,
				width = 300,
				height = 140
			},
		
			{
				x = 603,
				y = 0,
				width = 300,
				height = 130
			},
		
		},
		
		sheetContentWidth = 1024,
		sheetContentHeight = 1024
	}

	return options
end
M.getSheetOptions = getSheetOptions

return M